from __future__ import annotations

from collections.abc import Iterable
from typing import Any


ADE20K_LABELS = [
    "wall",
    "building",
    "sky",
    "floor",
    "tree",
    "ceiling",
    "road",
    "bed",
    "windowpane",
    "grass",
    "cabinet",
    "sidewalk",
    "person",
    "earth",
    "door",
    "table",
    "mountain",
    "plant",
    "curtain",
    "chair",
    "car",
    "water",
    "painting",
    "sofa",
    "shelf",
    "house",
    "sea",
    "mirror",
    "rug",
    "field",
    "armchair",
    "seat",
    "fence",
    "desk",
    "rock",
    "wardrobe",
    "lamp",
    "bathtub",
    "railing",
    "cushion",
    "base",
    "box",
    "column",
    "signboard",
    "chest of drawers",
    "counter",
    "sand",
    "sink",
    "skyscraper",
    "fireplace",
    "refrigerator",
    "grandstand",
    "path",
    "stairs",
    "runway",
    "case",
    "pool table",
    "pillow",
    "screen door",
    "stairway",
    "river",
    "bridge",
    "bookcase",
    "blind",
    "coffee table",
    "toilet",
    "flower",
    "book",
    "hill",
    "bench",
    "countertop",
    "stove",
    "palm",
    "kitchen island",
    "computer",
    "swivel chair",
    "boat",
    "bar",
    "arcade machine",
    "hovel",
    "bus",
    "towel",
    "light",
    "truck",
    "tower",
    "chandelier",
    "awning",
    "streetlight",
    "booth",
    "television receiver",
    "airplane",
    "dirt track",
    "apparel",
    "pole",
    "land",
    "bannister",
    "escalator",
    "ottoman",
    "bottle",
    "buffet",
    "poster",
    "stage",
    "van",
    "ship",
    "fountain",
    "conveyer belt",
    "canopy",
    "washer",
    "plaything",
    "swimming pool",
    "stool",
    "barrel",
    "basket",
    "waterfall",
    "tent",
    "bag",
    "minibike",
    "cradle",
    "oven",
    "ball",
    "food",
    "step",
    "tank",
    "trade name",
    "microwave",
    "pot",
    "animal",
    "bicycle",
    "lake",
    "dishwasher",
    "screen",
    "blanket",
    "sculpture",
    "hood",
    "sconce",
    "vase",
    "traffic light",
    "tray",
    "ashcan",
    "fan",
    "pier",
    "crt screen",
    "plate",
    "monitor",
    "bulletin board",
    "shower",
    "radiator",
    "glass",
    "clock",
    "flag",
]


ID2LABEL = {idx: label for idx, label in enumerate(ADE20K_LABELS)}
LABEL2ID = {label: idx for idx, label in ID2LABEL.items()}
WATER_RELATED_LABEL_NAMES = tuple(
    label
    for label in ADE20K_LABELS
    if label in {"water", "sea", "river", "lake", "waterfall", "swimming pool", "fountain"}
)

# Official OneFormer ADE20K thing class ids, kept here so we can rebuild the
# processor metadata without depending on an extra downloaded JSON file.
ONEFORMER_ADE20K_THING_IDS = (
    7,
    8,
    10,
    12,
    14,
    15,
    18,
    19,
    20,
    22,
    23,
    24,
    27,
    30,
    31,
    32,
    33,
    35,
    36,
    37,
    38,
    39,
    41,
    42,
    43,
    44,
    45,
    47,
    49,
    50,
    53,
    55,
    56,
    57,
    58,
    62,
    64,
    65,
    66,
    67,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    78,
    80,
    81,
    82,
    83,
    85,
    86,
    87,
    88,
    89,
    90,
    92,
    93,
    95,
    97,
    98,
    102,
    103,
    104,
    107,
    108,
    110,
    111,
    112,
    115,
    116,
    118,
    119,
    120,
    121,
    123,
    124,
    125,
    126,
    127,
    129,
    130,
    132,
    133,
    134,
    135,
    136,
    137,
    138,
    139,
    142,
    143,
    144,
    146,
    147,
    148,
    149,
)


def build_oneformer_ade20k_metadata() -> dict[str, Any]:
    metadata: dict[str, Any] = {str(idx): label for idx, label in enumerate(ADE20K_LABELS)}
    metadata["thing_ids"] = list(ONEFORMER_ADE20K_THING_IDS)
    metadata["class_names"] = list(ADE20K_LABELS)
    return metadata


def resolve_label_ids(label_names: Iterable[str]) -> tuple[list[int], list[str]]:
    label_ids: list[int] = []
    missing: list[str] = []
    for name in label_names:
        label_id = LABEL2ID.get(name)
        if label_id is None:
            missing.append(name)
            continue
        label_ids.append(label_id)
    return label_ids, missing
